apiVersion: mcm.ibm.com/v1alpha1
kind: PlacementPolicy
metadata:
  name: guestbook-gbapp
  labels:
    app: "gbapp"
    servicekind: CacheService
spec:
  clusterReplicas: 1
  clusterLabels:
    matchLabels:
      datacenter: dc1
  resourceHint:
    type: cpu
