apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: guestbook-gbapp
  labels:
    name: guestbook-gbapp
spec:
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - gbapp
      - gbf
      - gbrm
      - gbrs
  componentKinds:
  - group: core
    kind: Pods
